### ISSUE TITLE
discrepancy between repository and cookbook through supermarket api

### ISSUE THREAD

**Issue by Zhann** [opscode-cookbooks/apt#109]
If you look here, you'll see package mailutils being set:
https://github.com/opscode-cookbooks/apt/blob/master/recipes/unattended-upgrades.rb#L32

However, if you fetch apt cookbook through https://supermarket.getchef.com, you'll see the package resource is not there.

Both are apt cookbook version 2.6.0.

This seems like a version bump or cookbook upload gone wrong or something? Or how does this work?

**Comment by thommay** [comment]
This should be resolved with the release of 2.7.0
