### ISSUE TITLE
apt::default tricked by old update-success_stamp

### ISSUE THREAD

**Issue by jdblack** [opscode-cookbooks/apt#119]
apt:default intentionally does not run apt-get update if /var/lib/apt/periodic/update-success-stamp is present.

This can be a bit of a problem if a system is being bootstrapped for the first time and apt-get update has not been run in some time.   This can often be the case with hosted providers such as digital ocean.

$ date
Sun Feb  1 14:34:12 PST 2015
$ cd /var/lib/apt/periodic
$ ls -al update-success-stamp
-rw-r--r-- 1 root root    0 Jan  8 13:33 update-success-stamp

**Comment by meineerde** [comment]
The `execute[apt-get-update-periodic]` later in the recipe checks the timestamp of the file and should execute `apt-get update` if the mtime of the file is too old (24 hours by default).

It is not really clear to me why this didn't work for you. Could you possibly provide additional information, including the result of the guards checked for the various resources?

**Comment by jdblack** [comment]
This appears to be WORKS_AS_INTENDED.   I caused the problem.  I configured build-essential to run during compile phase without configuring the apt with compile_time_update.
