### ISSUE TITLE
apt_repository LWRP does not accept http_proxy

### ISSUE THREAD

**Issue by dbaggott** [opscode-cookbooks/apt#134]
The [documentation](https://github.com/opscode-cookbooks/apt#attribute-parameters) appears to indicate that apt_repository LWRP accepts an attribute parameter named `key_proxy`.  It does not and trying to do so produces the expected error:

`ERROR: undefined method `key_proxy' for Chef::Resource::AptRepository`

You *can* use a proxy by setting the `node['apt']['key_proxy']` attribute; you just can't pass the attribute directly to the apt_repository LWRP.

At a minimum, the documentation should be updated but, ideally, the apt_repository should be enhanced to accept the `key_proxy` parameter.

**Comment by thommay** [comment]
Fixed by #135

**Comment by evandhoffman** [comment]
Any idea when this fix will be available in Supermarket?
