### ISSUE TITLE
APT key not installed

### ISSUE THREAD

**Issue by goacid** [opscode-cookbooks/apt#141]
I've report a bug on another cookbooks and it seems it comes from this one.
https://github.com/chef/chef/issues/2866
Could you take a look ?

**Comment by sebaacuna** [comment]
I've also run into this and tracked it down to an issue with the default locale. The issue dissapears if the system's default locale is `en_US.utf8`.

Can you confirm is this is the problem you have? What is/was the default locale on your system?

**Comment by mapi** [comment]
I met same problem in debian system.
apt recipe execute `apt-key` command with `LANG=en_US`. But if `LC_ALL` already configured, `LANG=en_US` is ignored. ( `LC_ALL` takes precedence.)

https://github.com/opscode-cookbooks/apt/blob/488b07fd46aba20e675af34b6fbecededaae7878/providers/repository.rb#L53

**Comment by BarthV** [comment]
:+1:  here !

Same issue. Same reasons.

The fingerprint parser is only parsing ```"Key fingerprint ="``` output from ```apt-key finger``` cmd. : 
* https://github.com/opscode-cookbooks/apt/blob/master/providers/repository.rb#L56


Even if the test is forcing ```LANG = 'en_US'``` it's still not enough to have a good english output ...

```so = Mixlib::ShellOut.new(cmd, env: { 'LANG' => 'en_US' })```
* https://github.com/opscode-cookbooks/apt/blob/master/providers/repository.rb#L53

If you need to force EN locale you have to do a little bit more than just setting LANG : 
* you need to set both ```LANG``` & ```LANGUAGE``` env var

```bash
# locale
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=fr_FR.UTF-8

# apt-key finger
pub   2048R/8167EE24 2014-05-21
      Empreinte de la clef = 13CF DE6D D9EE 9784 F41A  F0F6 70E4 618A 8167 EE24
uid                  MariaDBManager

# export LANG='en_US'
# apt-key finger
pub   2048R/8167EE24 2014-05-21
      Empreinte de la clef = 13CF DE6D D9EE 9784 F41A  F0F6 70E4 618A 8167 EE24
uid                  MariaDBManager

# export LANG='en_US' && export LANGUAGE='en_US'
pub   2048R/8167EE24 2014-05-21
      Key fingerprint = 13CF DE6D D9EE 9784 F41A  F0F6 70E4 618A 8167 EE24
uid                  MariaDBManager
```

**Comment by BarthV** [comment]
:up:
