### ISSUE TITLE
Ability to set `sensitive` attribute. 

### ISSUE THREAD

**Issue by kwilczynski** [opscode-cookbooks/apt#150]
It would be nice to be able to specify `sensitive` attribute with `apt_repository` so that it will be handed down to the underlying `file` resource. Sometimes you need to add _user_ and _password_ when having to setup a vendor repository that used simple HTTP authentication. Hiding these would be a splendid feature to have.

Let me know @thommay, if you fancy a pull request for this.

**Comment by thommay** [comment]
:+1: would love one!

**Comment by kwilczynski** [comment]
@thommay OK :)

**Comment by kwilczynski** [comment]
@thommay assign me to this issue, so I can track it, if you don't mind.

**Comment by thommay** [comment]
@kwilczynski irritatingly I can't, unless you're happy to have commit bits on here?

**Comment by kwilczynski** [comment]
@thommay what if you add me to `opscode-cookbooks`? I hope there isn't a cliche around this - in the end, I am ex-Chef :) Let me know.

**Comment by kwilczynski** [comment]
@thommay closed in #160. Sorry for the delay!

**Comment by thommay** [comment]
@kwilczynski no problemo, thanks much!

**Comment by kwilczynski** [comment]
@thommay there will be another Pull Request to update documentation.
