### ISSUE TITLE
Backwards Compatibility Break

### ISSUE THREAD

**Issue by Rockstar04** [opscode-cookbooks/apt#153]
https://github.com/opscode-cookbooks/apt/commit/ea17f0bd7650b65337759ee80fa9ecb7799597d1 introduced a potential backwards compatibility break when using the apt_repository lwrp.

Before, the full protocol and port were required to be defined (only when no proxy was used it seems), now that they are automatically added this is causing duplicate protocols and ports to be added causing converge failures.

**Comment by Rockstar04** [comment]
I am working on a PR to allow the "new" and "old" ways to define the key server

**Comment by Rockstar04** [comment]
#154  was merged, if we could get a patch number bump everything will be golden

**Comment by thommay** [comment]
Pushed and released, thank you!

**Comment by Rockstar04** [comment]
No sir, thank you for getting to this so quickly.
