### ISSUE TITLE
Doesn't work on modern debian (jessie)

### ISSUE THREAD

**Issue by jsirex** [opscode-cookbooks/apt#80]
```
================================================================================
Error executing action `install` on resource 'package[update-notifier-common]'

================================================================================

Chef::Exceptions::Package
-------------------------
update-notifier-common has no candidate in the apt-cache

Resource Declaration:

---------------------
# In /tmp/kitchen/cache/cookbooks/apt/recipes/default.rb

68: package 'update-notifier-common' do
69:notifies :run, 'execute[apt-get-update]', :immediately
70:only_if { apt_installed? }

71: end
72:
```
Seems like package *update-notifier-common* has been removed. 
Or I missed something?

**Comment by meineerde** [comment]
Debian Jessie is going to become stable in probably less than a month (give or take). As this cookbook is used in about all setups, it would be crucial to resolve this issue until Jessie is stable.

There are now two different alternatives to solve this issue in #115 and #121. It would be great if you could comment on the issue and work with the community to resolve this hard incompatibility.

**Comment by fnawroth** [comment]
Could you please raise the priority on this issue? It's becoming a pain, since it blocks early-on testing on Jessie RC.

It seems that the authors of both pull requests agree that the latest version of #121 is the way to go.

**Comment by someara** [comment]
@thommay can you take a look at this?
